### ISSUE TITLE
Fullscreen programs take up space in the tile grid

### ISSUE THREAD

**Issue by kemmeo** [rustysec/tidalwm#35] opened 2020-03-01 10:25 UTC
Playing minecraft and working at the same time is hard when minecraft still takes up a tile grid space ;)
![super serious work](https://i.imgur.com/f8tLTZA.jpg)

**Comment by rustysec** [comment] 2020-03-01 15:12
What's your desired workflow? You could move Minecraft to another workspace? Or float it (`ctrl+alt+f` by default)?

Thanks for the report!

**Comment by kemmeo** [comment] 2020-03-01 15:39
Definitely want to float it. Thanks for responding so fast!

**Comment by rustysec** [comment] 2020-03-01 16:22
Have you tried the floating shortcut? If it solves your problem I'll close this issue.

**Comment by kemmeo** [comment] 2020-03-01 21:49
Sorry, I did try it but it did not solve the issue

**Comment by rustysec** [comment] 2020-03-01 21:50
Meaning it didn't float the window?

**Comment by kemmeo** [comment] 2020-03-01 22:17
Yes sorry, that is exactly what I mean

**Comment by rustysec** [comment] 2020-03-02 00:55
Well that is odd, I float windows all the time... Maybe if you do `journalctl -xf /usr/bin/gnone-shell` while you are trying the float shortcut you'll see an error of some kind. What is your shortcut set to (you can find it in the extension settings through `gnome-tweaks`)?

**Comment by rustysec** [comment] 2020-03-06 00:24
Ok, I added a blanket "ignore windows that are in fullscreen mode" which seems to fix your use case. You even got me to install minecraft to test. If you pull latest and restart gnome you should see more desirable behavior. Let me know if it's what you expected!

**Comment by rustysec** [comment] 2020-03-10 00:13
Going to go ahead and close this out as I believe it's now working as intended.

**Closed by rustysec** 2020-03-10 00:13 UTC
Labels: investigate
