### ISSUE TITLE
Attaching new monitor breaks tidal

### ISSUE THREAD

**Issue by rustysec** [rustysec/tidalwm#11] opened 2020-01-24 15:41 UTC
Tidal does an ok job of handling re-organization when an existing monitor is unplugged and reattached, it does survive if a _new_ monitor shows up after it has already initialized.

**Comment by REIS0** [comment] 2020-01-26 02:15
Okay i was just going to open another issue related to this
Looks like the tilling when I open an application that is already assigned to my second monitor the tilling gets really buggy, and stop working in some other workspaces in my main monitor

**Comment by rustysec** [comment] 2020-01-26 03:25
Hrm, I'm not sure. I use 2 external monitors every day, do you have steps to reproduce what you're experiencing?

This bug is specifically when I start up with no external monitors attached, then plug one in tiling doesn't kick in for the new monitor.

Appreciate you contributing new information!

**Comment by REIS0** [comment] 2020-01-26 03:56
Well for now I don't know what exactly is happening, so far it happened when I tried to open for example telegram and whatsdesk, and both are designed to open in my second monitor, sometimes they both open in full screen one above the other and sometimes the whatsdesk is smaller than it should, maybe is an electron bug I really don't know exactly.

**Comment by rustysec** [comment] 2020-01-26 04:04
I'll definitely look into it, how are they being assigned to that monitor?

**Comment by REIS0** [comment] 2020-01-26 04:16
I just open them and move them to another monitor, when I logout and login (or reboot whatever) they open on the monitor they were moved to last time.

**Comment by rustysec** [comment] 2020-01-26 04:22
Seems easy enough to reproduce, I'll play around with some electron apps and see what I can figure out. Thanks for the report.

**Comment by REIS0** [comment] 2020-01-26 20:09
Looks like i got to reproduce it but it was when I installed a new extension, after rebooting it was fixed.

**Closed** 2020-01-28 14:15 UTC
Labels: bug
